# Generated by Django 4.0.6 on 2022-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='passwd',
        ),
        migrations.AddField(
            model_name='member',
            name='CTC',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='skills',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
