# Generated by Django 4.0.6 on 2022-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_member_passwd_member_ctc_member_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='inputGroupFile01',
            field=models.FileField(blank=True, upload_to='doc'),
        ),
    ]
