# Generated by Django 4.0.6 on 2022-11-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_member_inputgroupfile01'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='inputGroupFile01',
            new_name='inputGroupFileAddon01',
        ),
    ]
