# Generated by Django 4.0.6 on 2022-11-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_inputgroupfile01_member_inputgroupfileaddon01'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='inputGroupFileAddon01',
            new_name='inputGroupFile02',
        ),
    ]
