# Generated by Django 4.0.6 on 2022-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_inputgroupfileaddon01_member_inputgroupfile02'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='inputGroupFile02',
        ),
        migrations.AddField(
            model_name='member',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
