# Generated by Django 4.0.6 on 2022-11-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_member_inputgroupfile02_member_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='file',
            field=models.FileField(upload_to='database2\\documents'),
        ),
    ]
