# Generated by Django 4.0.6 on 2022-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_member_file_member_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='CTC',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='Experience',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
