# Generated by Django 4.0.6 on 2022-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_member_ctc_alter_member_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('CTC', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='jobAspirents/')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='CTC',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='Experience',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
