# Generated by Django 4.0.6 on 2022-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_resume_alter_member_ctc_alter_member_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(default=None, null=True, upload_to='jobAspirents/'),
        ),
    ]
